// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0unhqVSEotLYHGvnW0w-10jQx1MQGtxA',
    appId: '1:729936702417:web:00f2695dd08fd554834ef0',
    messagingSenderId: '729936702417',
    projectId: 'lactoview-13e4c',
    authDomain: 'lactoview-13e4c.firebaseapp.com',
    storageBucket: 'lactoview-13e4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmV-i8jrUknPjaAMHX68u2O2zs6XytvpE',
    appId: '1:729936702417:android:8e1fc1bc6c0b5d68834ef0',
    messagingSenderId: '729936702417',
    projectId: 'lactoview-13e4c',
    storageBucket: 'lactoview-13e4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVfevg4QTIAc9ptumg3yar3SOrCQbYu5Y',
    appId: '1:729936702417:ios:f0f9d662109d19f8834ef0',
    messagingSenderId: '729936702417',
    projectId: 'lactoview-13e4c',
    storageBucket: 'lactoview-13e4c.firebasestorage.app',
    iosBundleId: 'com.example.lactoView',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVfevg4QTIAc9ptumg3yar3SOrCQbYu5Y',
    appId: '1:729936702417:ios:f0f9d662109d19f8834ef0',
    messagingSenderId: '729936702417',
    projectId: 'lactoview-13e4c',
    storageBucket: 'lactoview-13e4c.firebasestorage.app',
    iosBundleId: 'com.example.lactoView',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0unhqVSEotLYHGvnW0w-10jQx1MQGtxA',
    appId: '1:729936702417:web:3488d2580d40525b834ef0',
    messagingSenderId: '729936702417',
    projectId: 'lactoview-13e4c',
    authDomain: 'lactoview-13e4c.firebaseapp.com',
    storageBucket: 'lactoview-13e4c.firebasestorage.app',
  );
}
